### PR TITLE
handle error corner cases

### PR DESCRIPTION
**Pull request by jmcclelland**
When stripe throws an error, and the original form as an onclick event,
we briefly see the error before the form is submitted according to
the onclick event (i.e. the PreventDefault() and return false
does not have any effect).

This fix removes any onclick attributes at the beginning and only
re-adds them and resubmits the form if we should.

### CODE REVIEW

**Comment by jmcclelland** [comment]
I'm not sure this is the right fix - but not sure what else to do. We have received two complaints from people getting "No such token: Stripe Token".

I don't know why it's happening for our users, but I was able to replicate it by submitting a test Visa card number on a live site.

When that happens, the javascript submission to stripe returns an error (and the Stripe Token field is still populated with "Stripe Token" rather than an actual token).

Unfortunately, the form is still submitted (since there is a onclick event handler added directly to the form). 

As a result, we can't see the error and rather than getting a helpful error message we get the confusing token one.

**Comment by jmcclelland** [comment]
And one more thing... for testing purposes, the "submitOnce" onclick event is added to a contribution only if the confirmation page is disabled (see CRM_Contribute_Form_Contribution_Main::buildQuickForm())

**Comment by mattwire** [comment]
Have you tested this with drupal webform?  I think it might break the "back" buttons on a multipage form?

**Comment by jmcclelland** [comment]
I just finished a full test using a multi-page web form - back/forward buttons worked properly. Tested using both test card, legit card with bad expiration date, and working card.

**Pull request merged**
